### ISSUE TITLE
External messages to left

### ISSUE THREAD

**Issue by EpsilonOrionis** [nkzawa/socket.io-android-chat#1]
Hi, I would show external messages from the outside on the left side of the screen and messages sent by the myself on the right side of the screen. I've created two different item_message for the right side and for the left side, but I don't know how to implement this. Could you help me with a code snippet?
Thank you in advance.

**Comment by Salvatorie** [comment]
public class MessagesListAdapter extends BaseAdapter {
 
    private Context context;
    private List<Message> messagesItems;
 
    public MessagesListAdapter(Context context, List<Message> navDrawerItems) {
        this.context = context;
        this.messagesItems = navDrawerItems;
    }
 
    @Override
    public int getCount() {
        return messagesItems.size();
    }
 
    @Override
    public Object getItem(int position) {
        return messagesItems.get(position);
    }
 
    @Override
    public long getItemId(int position) {
        return position;
    }
 
    @SuppressLint("InflateParams")
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
 
        /**
         * The following list not implemented reusable list items as list items
         * are showing incorrect data Add the solution if you have one
         * */
 
        Message m = messagesItems.get(position);
 
        LayoutInflater mInflater = (LayoutInflater) context
                .getSystemService(Activity.LAYOUT_INFLATER_SERVICE);
 
        // Identifying the message owner
        if (messagesItems.get(position).isSelf()) {
            // message belongs to you, so load the right aligned layout
            convertView = mInflater.inflate(R.layout.list_item_message_right,
                    null);
        } else {
            // message belongs to other person, load the left aligned layout
            convertView = mInflater.inflate(R.layout.list_item_message_left,
                    null);
        }
 
        TextView lblFrom = (TextView) convertView.findViewById(R.id.lblMsgFrom);
        TextView txtMsg = (TextView) convertView.findViewById(R.id.txtMsg);
 
        txtMsg.setText(m.getMessage());
        lblFrom.setText(m.getFromName());
 
        return convertView;
    }
}

Founded in http://www.androidhive.info/2014/10/android-building-group-chat-app-using-sockets-part-2/

**Comment by EpsilonOrionis** [comment]
I knew this. The problem is that in this project he's using a normal listview, not a recyclerview. In this case it's easier to implement this, but i don't know what to do in our case...
Thanks

**Comment by nkzawa** [comment]
Please see the doc for RecyclerView. Sorry but I think it's not good to explain about the detail of Android development here.

https://developer.android.com/training/material/lists-cards.html
