### ISSUE TITLE
Always getting Connect_error

### ISSUE THREAD

**Issue by saisworld** [nkzawa/socket.io-android-chat#15]
Hi,

I downloaded you source code and changed the CHAT_SERVER_URL to my localhost nodejs socket io instance and its always throwing error Connect_error. I tried with connecting to my localhost server using the plain html for testing purpose and it worked without any issues. Could you please check where I'm doing wrong?

server code: v.1.3.6

    // usernames which are currently connected to the chat
    var usernames = {};
    var numUsers = 0;

    var io = require('socket.io')(server);
    io.on('connection', function (socket) {
	  var addedUser = false;
	  console.log("connected");

	  // when the client emits 'new message', this listens and executes
	  socket.on('new message', function (data) {
	    // we tell the client to execute 'new message'
	    socket.broadcast.emit('new message', {
	      username: socket.username,
	      message: data
	    });

	    console.log(data);
	  });

	  // when the client emits 'add user', this listens and executes
	  socket.on('add user', function (username) {
	    // we store the username in the socket session for this client
	    socket.username = username;
	    // add the client's username to the global list
	    usernames[username] = username;
	    ++numUsers;
	    addedUser = true;
	    socket.emit('login', {
	      numUsers: numUsers
	    });
	    // echo globally (all clients) that a person has connected
	    socket.broadcast.emit('user joined', {
	      username: socket.username,
	      numUsers: numUsers
	    });
	  });

	  // when the client emits 'typing', we broadcast it to others
	  socket.on('typing', function () {
	    socket.broadcast.emit('typing', {
	      username: socket.username
	    });
	  });

	  // when the client emits 'stop typing', we broadcast it to others
	  socket.on('stop typing', function () {
	    socket.broadcast.emit('stop typing', {
	      username: socket.username
	    });
	  });

	  // when the user disconnects.. perform this
	  socket.on('disconnect', function () {
	    // remove the username from global usernames list
	    if (addedUser) {
	      delete usernames[socket.username];
	      --numUsers;

	      // echo globally that this client has left
	      socket.broadcast.emit('user left', {
	        username: socket.username,
	        numUsers: numUsers
	      });
	    }
	  });
  });

My test index.html file -

                <script src="https://cdn.socket.io/socket.io-1.3.5.js"></script>
                <script type="text/javascript">
                 var socket = io.connect('http://localhost:9000');
                //socket.connect();
               socket.on('connect', function() {
                         console.log('connected');
                 });

                  socket.emit("new message", "Test message from client");		

              </script>

**Comment by nkzawa** [comment]
Let me know how did you change the value of `CHAT_SERVER_URL`. Usually, you have to set IP of your PC.

**Comment by saisworld** [comment]
Worked perfectly. Thanks
