### ISSUE TITLE
how to use websocket transaction instead of polling transaction?

### ISSUE THREAD

**Issue by hamberluo** [nkzawa/socket.io-android-chat#17]

**Comment by nkzawa** [comment]
The library automatically uses websocket if it'a available. First, polling transport is used and upgraded to websocket.
If you'd like to force websocket, set the `transports` option.

**Comment by hamberluo** [comment]
in my case it dont automatically uses websocket, i use http.
how to set transports option?

thanks

**Comment by tux-world** [comment]
@hamberluo could you fix this problem? i have the same problem

**Comment by tux-world** [comment]
@nkzawa how can i set normally?
