### ISSUE TITLE
JAR/Eclipse support?

### ISSUE THREAD

**Issue by cravindra** [nkzawa/socket.io-android-chat#2]
Hello.  Is there a JAR file or an eclipse project that can be used?

**Comment by Salvatorie** [comment]
Please!!!

**Comment by luongbs94** [comment]
How to import to eclipse

**Comment by icaroabreu** [comment]
Use this library https://github.com/cmarrero01/socket.io-client.java
Really saved my life!

**Comment by oliguo** [comment]
why not use android studio

**Comment by cravindra** [comment]
@icaroabreu : Thanks for the link! That worked for me (more specifically, the Socket.io related JAR in the project's libs folder.)

@oliguo : Can't switch to Android Studio due to regulations at the place I work.
