### ISSUE TITLE
Issue in Socket.io android

### ISSUE THREAD

**Issue by waqary705** [nkzawa/socket.io-android-chat#26]
Sir I have an issue listen socket from server . You make for group chat but I want one-one lisntening from server or you can say private chat only one person chat to other person please tell me how do I manage this

**Comment by nkzawa** [comment]
Basically, this is done on server, by using `room` like http://stackoverflow.com/questions/23619015/creating-a-private-chat-between-a-key-using-a-node-js-and-socket-io
