### ISSUE TITLE
how to use a ip address and port number 

### ISSUE THREAD

**Issue by luoruiyi** [nkzawa/socket.io-android-chat#33]
Such as 192.168.0.1:8888

**Comment by siddharthgopi** [comment]
change it in ChatApplication.java  in  app/src/main/java

like this:

        try {
//            mSocket = IO.socket(Constants.CHAT_SERVER_URL);
            mSocket = IO.socket("http://192.168.0.1:8888");

**Comment by nkzawa** [comment]
yep, thanks @siddharthgopi
