### ISSUE TITLE
Can not setup port with IO.Options

### ISSUE THREAD

**Issue by cougar0828** [nkzawa/socket.io-android-chat#39]
Hello, 

  I can't setup port with IO.Options in Android, When socket.connect(), it always connect to port 80,

  try to add port in host url > "http://host : port", but useless, and i use example both Node.js server

  and Android, Node.js can get port 3000, Android's socket.connect() can't...
 
  Could someone know this issue ? many thanks!!

**Comment by nkzawa** [comment]
Please post how your setup looks like.

**Comment by nkzawa** [comment]
Closed due to inactivity.
