### ISSUE TITLE
Does it support namespace?

### ISSUE THREAD

**Issue by zy532410321** [nkzawa/socket.io-android-chat#8]
Hi nkzawa,
May I know if this lib support namespace ?
Need to integration with nodejs server, Automattic/socket.io.
Thanks.

**Comment by nkzawa** [comment]
The library supports namespace. Usage is almost the same with the JS client.

```java
socket = IO.socket("http://somewhere/your-namespace");
```

**Comment by zy532410321** [comment]
Hi nkzawa,
Tested, socket = IO.socket("http://somewhere/your-namespace"); not works
Write like this works fine:
            IO.Options options = new IO.Options();
            options.path = "/socket.io";
            options.query = "userid="+userId;
            mSocket = IO.socket("http://test:3000", options);
            Socket namespaceSocket =new Socket(mSocket.io(),"/aiocsu-chat");
First init a socket without namespace, then new a socket with previous socket's io and namespace link

**Comment by rajradjasegar** [comment]
Hello, 

@nkzawa Thank you, your snippet is working for me with socket.io java client version 1.0 
`compile ('io.socket:socket.io-client:1.0.0') {
        // excluding org.json which is provided by Android
        exclude group: 'org.json', module: 'json'
    }`

@All android developpers : Please use this client if you want to use namespace and send between mobile client long messages or JSON Object. 

@zy532410321 thank you for your answer also, your snippet worked for me also but only  with older version of the client 
`compile 'com.github.nkzawa:socket.io-client:0.3.0'` 

But the issue when I was using your snippet, clients were not able to exchange between them long messages and JSON object, I had this error :
`(HTTPLog)-Static: isSBSettingEnabled `
It looks like the older client didn't accept the receiving data. if someone knows what is really the problem linked to that message, please share it with us. 
  
So I had to upgrade and use nkzawa snippet and it worked.
