### ISSUE TITLE
i dont find import com.github.nkzawa.emitter.Emitter;

### ISSUE THREAD

**Issue by muafakul** [nkzawa/socket.io-android-chat#9]
This code is error 

import com.github.nkzawa.emitter.Emitter;

Please help me ..please fix this

**Comment by nkzawa** [comment]
Need to Install all dependencies. I strongly recommend to use gradle for resolving them but you'd like to do manually, please see http://nkzawa.github.io/socket.io-client.java/dependencies.html.

**Comment by muafakul** [comment]
Please... i dont use grandle ... iam developing android app using Aide(android ide) ....please ..i need .jar file ....very very please

**Comment by muafakul** [comment]
WOWOW..iGot it ...yes i can ..very thanks :D

**Comment by vsavvos** [comment]
i have the same issue. please tell me how resolved that problem? Thank you
